# Generated by Django 2.2.6 on 2019-10-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_introduction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
