# Generated by Django 2.2.6 on 2019-10-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excution', '0002_auto_20191030_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_introduction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
