# Generated by Django 2.2.4 on 2019-08-19 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('회칙', '회칙'), ('안건지/회의록', '안건지/회의록')], max_length=50)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('text', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='info_photo/%Y/%m/%d')),
                ('file', models.FileField(blank=True, upload_to='info_file/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_info_minutes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
