# Generated by Django 2.2.4 on 2019-08-21 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('informations', '0002_auto_20190821_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_bylaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bylaw', 'bylaw')], max_length=50)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('text', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='info_photo/%Y/%m/%d')),
                ('file', models.FileField(blank=True, upload_to='info_file/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_info_bylaw', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post_minutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('minutes', 'minutes')], max_length=50)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('text', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='info_photo/%Y/%m/%d')),
                ('file', models.FileField(blank=True, upload_to='info_file/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_info_minutes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
