# Generated by Django 2.2.4 on 2019-08-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0003_auto_20190822_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated']},
        ),
    ]
