# Generated by Django 2.2.6 on 2019-10-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0004_auto_20190823_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('his', 'his')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
