# Generated by Django 2.2.6 on 2019-10-30 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0005_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
